Update test-connection.yml

diff --git a/.github/workflows/test-connection.yml b/.github/workflows/test-connection.yml
--- a/.github/workflows/test-connection.yml
+++ b/.github/workflows/test-connection.yml
@@ -56,13 +56,13 @@ jobs:
         fi
         EOF
 
-    - name: Check Key Format
-      run: |
-        if [[ "${SECRET_KEY}" == '{"'* ]]; then
-          echo "Key appears to be JSON format"
-        else
-          echo "Key is not in JSON format"
-        fi
+    # - name: Check Key Format
+    #   run: |
+    #     if [[ "${SECRET_KEY}" == '{"'* ]]; then
+    #       echo "Key appears to be JSON format"
+    #     else
+    #       echo "Key is not in JSON format"
+    #     fi
     
     - name: Install and configure YC CLI
       run: |
@@ -75,18 +75,18 @@ jobs:
         mv yc $HOME/yandex-cloud/bin/
         echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
         echo "Ok"
-    #     # 2. Проверка ключа перед использованием
-    #     echo "Validating service account key..."
-    #     echo "${{ secrets.YC_SA_KEY }}" > sa-key.json
-    #     if ! jq empty sa-key.json; then
-    #       echo "❌ Invalid JSON format in YC_SA_KEY"
-    #       exit 1
-    #     fi
+        # 2. Проверка ключа перед использованием
+        echo "Validating service account key..."
+        echo "${{ secrets.YC_SA_KEY }}" > sa-key.json
+        if ! jq empty sa-key.json; then
+          echo "❌ Invalid JSON format in YC_SA_KEY"
+          exit 1
+        fi
         # 3. Конфигурация YC CLI
-        # echo "Configuring YC CLI..."
-        # $HOME/yandex-cloud/bin/yc config set service-account-key sa-key.json
-        # $HOME/yandex-cloud/bin/yc config set folder-id b1gbg64nvnbues4n0i9k
-        # $HOME/yandex-cloud/bin/yc config set compute-default-zone ru-central1-a
+        echo "Configuring YC CLI..."
+        $HOME/yandex-cloud/bin/yc config set service-account-key sa-key.json
+        $HOME/yandex-cloud/bin/yc config set folder-id b1gbg64nvnbues4n0i9k
+        $HOME/yandex-cloud/bin/yc config set compute-default-zone ru-central1-a
     
         # # 4. Проверка конфигурации
         # echo "Configuration details:"
