Update test-connection1.yml

diff --git a/.github/workflows/test-connection1.yml b/.github/workflows/test-connection1.yml
--- a/.github/workflows/test-connection1.yml
+++ b/.github/workflows/test-connection1.yml
@@ -21,16 +21,17 @@ jobs:
     #   run: yc config set service-account-key key.json
     - name: Install YC CLI
       run: |
-        # Установка yc с явным указанием директории установки
-        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i -b ~/yc-bin
-        echo "~/yc-bin" >> $GITHUB_PATH
+        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i
+        yc --version
+    #     curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i -b ~/yc-bin
+    #     echo "~/yc-bin" >> $GITHUB_PATH
         
-    - name: Configure YC CLI
-      run: |
-        # Используем полный путь к yc
-        ~/yc-bin/yc config set service-account-key key.json
-        ~/yc-bin/yc config list
+    # - name: Configure YC CLI
+    #   run: |
+    #     # Используем полный путь к yc
+    #     ~/yc-bin/yc config set service-account-key key.json
+    #     ~/yc-bin/yc config list
         
-        # Проверяем доступность yc через PATH
-        which yc || echo "yc not in PATH"
-        yc --version || echo "Failed to run yc from PATH"
+    #     # Проверяем доступность yc через PATH
+    #     which yc || echo "yc not in PATH"
+    #     yc --version || echo "Failed to run yc from PATH"
